yaml
title: Beata Kosmider Lab
url: https://beatakosmiderlab.github.io
baseurl: ""
remote_theme: alshedivat/al-folio

description: Dr. Kosmider's translational research centers on primary alveolar type II cells.
footer_text: © 2026 Beata Kosmider Lab. Powered by Jekyll and al-folio.
